[package]
name = "watt"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
edition = "2018"
publish = false
include = [
    "LICENSE_APACHE",
    "LICENSE_MIT",
    "runtime/LICENSE_ISC",
    "runtime/src",
    "src",
]

[workspace]
members = ["demo/client", "demo/wa"]
